language: node_js

node_js:
  - lts/*
  - node

os:
  - linux
  - osx
  # Re-add Windows to the config when Travis fixes it.
  # https://travis-ci.community/t/node-js-build-fails-with-no-obvious-error/961
  # - windows

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: lint
      script: yarn lint
      node_js: node
    - stage: build
      script: yarn build
      node_js: node
    - stage: release
      if: branch = master
      node_js: node
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release

stages:
  - lint
  - test
  - build
  - release
