language: node_js

node_js:
  - 8
  - 10

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - node_modules

script: yarn test:ci

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: build
      script: yarn build
    - stage: release
      if: branch = master
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release

stages:
  - lint
  - test
  - build
  - release
