language: node_js

node_js:
  - lts/*
  - node

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - node_modules

script: yarn test:ci

jobs:
  include:
    - stage: lint
      script: yarn lint
      node_js: node
    - stage: build
      script: yarn build
      node_js: node
    - stage: release
      if: branch = master
      node_js: node
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release

stages:
  - lint
  - test
  - build
  - release
