language: node_js

node_js:
  - 6
  - 8
  - 10

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: release
      if: branch = master
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
