name: Test and Build

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-node@v2.2.0
        with:
          node-version: 10
      - run: yarn install
      - run: yarn lint
      - run: yarn test
      - run: yarn build
